<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(1)_Cajas Organizadoras</name>
   <tag></tag>
   <elementGuidId>19acec1b-44b1-4783-94cf-83062be003c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category-2-cajas-organizadoras</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div[4]/div/div/section/div[2]/div/div[2]/div/div[1]/div/div[3]/div/div/div[8]/div[3]/div/div[1]/div[21]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4afe9fb-4c35-4108-a5b6-23f428d74165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-checkbox__input h1 w1 absolute o-0 pointer</value>
      <webElementGuid>6fd7e223-cded-42f9-a29a-09194e4b24ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category-2-cajas-organizadoras</value>
      <webElementGuid>d481146a-1c2d-4431-90a9-d4bb11c4a310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cajas Organizadoras</value>
      <webElementGuid>5537c70f-d4fd-473d-a530-48c6b4141f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68a4659a-7b38-4d65-b02c-acca3dc1af74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d2f4f1e-ad96-407e-aa1a-af9afa86c345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cajas Organizadoras</value>
      <webElementGuid>7bd92b16-3937-460f-a635-2e66054f9734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-2-cajas-organizadoras&quot;)</value>
      <webElementGuid>ece056aa-55b5-41a2-8238-de8a41bd10c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category-2-cajas-organizadoras']</value>
      <webElementGuid>b5412e9e-152f-42a0-8c7c-6bbcfaee0dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div/div/div[25]/div/div/input</value>
      <webElementGuid>984fe29d-898c-4a8f-811c-83280f2482fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'category-2-cajas-organizadoras' and @name = 'Cajas Organizadoras' and @type = 'checkbox']</value>
      <webElementGuid>2a0b486d-84d6-4572-a9d2-b4c2d5e3576a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
