<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Finalizar compra</name>
   <tag></tag>
   <elementGuidId>dca5c57b-30d1-4d66-bee0-6b8941c9fe26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-to-orderform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div/div[2]/div/table/tfoot/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e1ca531-a86b-4a0c-b594-4ca834b681fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/orderform</value>
      <webElementGuid>d46e991c-876d-4783-8623-52e2b191d1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a3844907-932a-4ac9-975a-151fb905cb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>cartToOrderform</value>
      <webElementGuid>602e0259-3b21-47ff-bbc8-4b081437097e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-to-orderform</value>
      <webElementGuid>024e814f-ceb2-4969-af18-547e3a9a0694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-large btn-success pull-left-margin btn-place-order</value>
      <webElementGuid>0770686d-05c7-487b-a481-6898851f0b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>cart.finalize</value>
      <webElementGuid>72d25e42-6796-4088-9ef9-ea8adacf0499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: cart.next</value>
      <webElementGuid>da1d1a7b-9947-470e-8dc6-3cad07e1f24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar compra</value>
      <webElementGuid>b0fa68d5-ea54-47b6-a90f-a52ec116ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutMainContainer&quot;)/div[@class=&quot;container container-main container-cart&quot;]/div[@class=&quot;checkout-container row-fluid cart-active&quot;]/div[@class=&quot;cart-template full-cart span12 active&quot;]/div[@class=&quot;summary-template-holder&quot;]/div[@class=&quot;row-fluid summary&quot;]/div[@class=&quot;span5 totalizers summary-totalizers cart-totalizers pull-right&quot;]/div[2]/div[@class=&quot;accordion-group&quot;]/div[@class=&quot;accordion-body collapse in&quot;]/div[@class=&quot;accordion-inner&quot;]/table[@class=&quot;table&quot;]/tfoot[@class=&quot;total-cenco&quot;]/span[@class=&quot;btn-place-order-wrapper&quot;]/a[@id=&quot;cart-to-orderform&quot;]</value>
      <webElementGuid>34e0aea6-8c4f-411d-ade7-a89086497290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-to-orderform']</value>
      <webElementGuid>db0e2fad-8c31-41a7-ad33-28686be462cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='checkoutMainContainer']/div[4]/div[3]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/table/tfoot/span/a</value>
      <webElementGuid>c0ab826e-a344-4da7-afd0-8a6e42075895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Finalizar compra')]</value>
      <webElementGuid>8029208e-cf78-4397-b8e8-89aaea31b21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 49.990'])[5]/following::a[1]</value>
      <webElementGuid>08992361-5ecd-4e1d-9ab4-e2e11f689443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/following::a[1]</value>
      <webElementGuid>25cf84f2-1d9d-4f4e-9056-f698fe18b6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegir más productos'])[1]/preceding::a[1]</value>
      <webElementGuid>935f1231-3ef1-4464-ba4d-d453ce9df4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprimir'])[1]/preceding::a[2]</value>
      <webElementGuid>cf602ada-121e-4c96-966f-57262b73bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar compra']/parent::*</value>
      <webElementGuid>7436bb56-b836-4d4d-90e8-37b035d6662a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/orderform')]</value>
      <webElementGuid>f8e871d0-17fa-4afe-bb1d-44baab235ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/span/a</value>
      <webElementGuid>330bf4cf-938c-4dda-9917-ab6ebfe3e2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/orderform' and @id = 'cart-to-orderform' and (text() = 'Finalizar compra' or . = 'Finalizar compra')]</value>
      <webElementGuid>37da9af8-0b64-467e-83af-af08334a1d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
